CC=g++
OBJS=$(shell find . -maxdepth 1 -name "*.cpp" | sed s/.cpp/.o/)
FLAGS=-g -I dep/include/
LDFLAGS=-lallegro-5.0.0-RC4-monolith-mt -L dep/lib
#LDFLAGS=-lallegro-5.0.0-RC4-monolith-md-debug -L dep/lib
BIN=./game.exe
RM=rm
EXEC=exec

all: $(BIN)

.cpp.o:
	$(CC) $< -c $(FLAGS)

$(BIN): $(OBJS)
	$(CC) -o $@ $(OBJS) $(LDFLAGS)

run:
	$(EXEC) $(BIN)

clean:
	$(RM) *.o
	$(RM) $(BIN)
